version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: swiftlogistics_postgres
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: postgres   # default DB, we’ll use it to create others
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # run init SQL files at startup

volumes:
  postgres_data:
